name: Main Build

on:
  push:
    branches:
      - 'main'

jobs:
  semver-mgmt-build:
    name: Build ${{ github.ref_name }} ${{ github.ref_type }} in ${{ github.repository }} repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.11.1

      - name: Gradle build
        run: ./gradlew build

      - name: Bump version and push tag
        id: tagging
        uses: mathieudutour/github-tag-action@v6.1
        with:
          default_bump: patch
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.tagging.outputs.new_tag }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}
